### ISSUE TITLE
would you give us a model to eval

### ISSUE THREAD

**Issue by yjl9122** [SeitaroShinagawa/chainer-partial_convolution_image_inpainting#2]
would you give us a model to eval

**Comment by SeitaroShinagawa** [comment]
Hi @yjl9122,
Thank you for your attention. However, I will start a new training because I fixed some settings of partial convolution layer (added bias calculation and fixed filter size)  

Anyway, you can try my model (before fixing) trained with 500,000 iteration without fine-tuning stage.   
You can download it [here](https://drive.google.com/open?id=1Mcisfywpjq8aasHw2ELBMbrXTxsOJrtL)
  
To generate examples with the model, use [generate_result.py](https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/generate_result.py) as below,    
```python
python generete_result.py -g 0 --load_model model500000.npz  
```
Make sure that you need to replace [net_pre-trained.py](https://github.com/SeitaroShinagawa/chainer-partial_convolution_image_inpainting/blob/master/common/net_pre-trained.py) with net.py as below because latest net.py has been already fixed.  
```
mv common/net_pre-trained.py common/net.py
```  
Best,

**Comment by Prudvi01** [comment]
Hello @SeitaroShinagawa I don't have an Nvidia GPU so I'm using CPU by excluding (-g 0) but running the command 'python generete_result.py --load_model model500000.npz' still says shows the following error
![Screenshot 2019-08-23 at 6 30 44 PM](https://user-images.githubusercontent.com/29304096/63594497-32f27580-c5d4-11e9-94f5-7773bd91c993.jpg)
